### ISSUE TITLE
Исправить регулярное выражение в ChatCommandHandler

### ISSUE THREAD

**Issue by Anton-Khan** [FokusHuk/MakimaBot#38]
Там сейчас происходит магия вне Хогвартса!
Сейчас регулярка такая: ^@makima_daily_bot\s*([a-z]*)\s*(.*)$ 

#### Просто меншн бота -> сматчит и в группах пустые строки
| name   | parameter           | matchCount |
|--------|---------------------|------------|
| input: | "@makima_daily_bot" |            |
| match  | @makima_daily_bot   | 1 раз      |
| group1 | empty string        |            |
| group2 | empty string        |            |

#### Меншн бота написан слитно с командой -> сматчит и в группе 1 будет команда
| name   | parameter           | matchCount |
|--------|---------------------|------------|
| input: | "@makima_daily_bottest" |            |
| match  | @makima_daily_bottest   | 1 раз      |
| group1 | test        | 1 раз           |
| group2 | empty string        |            |

#### Меншн бота а после текст на Русском -> сматчит и в группе 2 будет текст 
| name   | parameter           | matchCount |
|--------|---------------------|------------|
| input: | "@makima_daily_bot тест" |            |
| match  | @makima_daily_bot тест   | 1 раз      |
| group1 | empty string         |           |
| group2 | тест        | 1 раз           |

#### Меншн бота а после текст на Английском -> сматчит и в группе 1 будет текст 
| name   | parameter           | matchCount |
|--------|---------------------|------------|
| input: | "@makima_daily_bot test" |            |
| match  | @makima_daily_bot test   | 1 раз      |
| group1 | test        | 1 раз           |
| group2 | empty string        |            |

**Comment by FokusHuk** [comment]
- [x] Дописать тесты на ChatCommandHandler
