### ISSUE TITLE
Запретить Макиме реагировать на пересланные сообшения!

### ISSUE THREAD

**Issue by Anton-Khan** [FokusHuk/MakimaBot#39]
Запретить Макиме реагировать на пересланные сообшения!

А что еще тут написать? Ну бот начал отвечать на пересланные сообщения из этого же чата. Зачем? Почему? - Непонятно, но нужно исправить.

**Comment by FokusHuk** [comment]
Ну мы словили баг на команду все таки
Я думаю просто на пересланыне пусть реагирует (в плане статистики)
тут поинт в том, что если ты пересылаешь сообщение с командой, то его выполнять не надо
просто проверочку воткнуть в shouldExecute
