### ISSUE TITLE
Канал для алертов

### ISSUE THREAD

**Issue by FokusHuk** [FokusHuk/MakimaBot#48]
Чтобы быстрее узнавать об ошибках на проде, переделаем нотификации
Вместо дейли ивента, который раз в день отправляет ошибки, будем репортить их сразу, в отдельный канал
Сообщение туда же
Заодно не будет перегружать стейт, бакет тоже не бесплатный так то хД

**Comment by FokusHuk** [comment]
Исключить тестовый канал и канал алертов из подсчета unknown messages

**Comment by Anton-Khan** [comment]
А точно нужно исключить ?

**Comment by FokusHuk** [comment]
А зачем их учитывать, они служебные
